StylesPath = ~/.config/vale/styles

MinAlertLevel = suggestion

Packages = Microsoft, write-good

[*.md]
BasedOnStyles = Vale, Microsoft, write-good

# Downgrade a few Microsoft rules that are too noisy for RFCs/technical docs
Microsoft.Headings = NO
Microsoft.Passive = suggestion
Microsoft.Wordiness = warning
