#!/usr/bin/env bash

ZSH_PLUGIN_DIR="$ZDOTDIR/plugins"

# Source plugins
source "$ZSH_PLUGIN_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$ZSH_PLUGIN_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# Source tooling integration
eval "$(fzf --zsh)"
eval "$(zoxide init zsh)"
